window.SEO_CONFIG = {
  baseUrl: 'https://www.noxafilmstudio.com',
  routes: {
    '/': {
      title: 'NOXA FILM - We Direct the Future of Cinema',
      description: 'NOXA Film Studio is an AI-native studio crafting cinematic worlds and premium trailers.',
      ogType: 'website',
      jsonLd: {
        '@context': 'https://schema.org',
        '@type': 'Organization',
        name: 'NOXA Film Studio',
        url: 'https://www.noxafilmstudio.com',
        logo: 'https://www.noxafilmstudio.com/favicon-48.png',
        sameAs: [
          'https://www.youtube.com/@noxafilm',
          'https://www.instagram.com/noxafilm/',
        ],
      },
    },
    '/ai-film-studio/': {
      title: 'AI Film Studio | NOXA FILM',
      description: 'NOXA Film Studio builds AI-native cinematic worlds and original film universes.',
      ogType: 'website',
    },
    '/trailer/': {
      title: 'Mars Empire Trailer | NOXA FILM',
      description: 'Watch the Mars Empire trailer from NOXA Film Studio.',
      ogType: 'video.other',
      jsonLd: {
        '@context': 'https://schema.org',
        '@type': 'VideoObject',
        name: 'Mars Empire Trailer',
        description: 'The last human fortress on Mars faces survival and power struggles in this cinematic trailer.',
        thumbnailUrl: 'https://www.noxafilmstudio.com/trailer/images/mars_trailer_thumbnail.png',
        uploadDate: '2025-01-01',
        duration: 'PT4M11S',
        embedUrl: 'https://www.noxafilmstudio.com/trailer/',
        contentUrl: 'https://www.noxafilmstudio.com/trailer/videos/mars_trailer.mp4',
      },
    },
    '/trailer2/': {
      title: 'The Forbidden Day Trailer | NOXA FILM',
      description: 'Watch the Forbidden Day trailer from NOXA Film Studio.',
      ogType: 'video.other',
      jsonLd: {
        '@context': 'https://schema.org',
        '@type': 'VideoObject',
        name: 'The Forbidden Day Trailer',
        description: 'A dual-sun world fractures as the forbidden hour arrives in this NOXA trailer.',
        thumbnailUrl: 'https://www.noxafilmstudio.com/trailer2/images/96209223-C529-4132-9238-8002ADD9B36E.PNG',
        uploadDate: '2025-01-01',
        duration: 'PT1M43S',
        embedUrl: 'https://www.noxafilmstudio.com/trailer2/',
        contentUrl: 'https://www.noxafilmstudio.com/trailer2/videos/forbidden_trailer.mp4',
      },
    },
    '/trailer3/': {
      title: 'Blade of Fate Trailer | NOXA FILM',
      description: 'Watch the Blade of Fate trailer from NOXA Film Studio.',
      ogType: 'video.other',
      jsonLd: {
        '@context': 'https://schema.org',
        '@type': 'VideoObject',
        name: 'Blade of Fate Trailer',
        description: 'A desert empire ruled by digital bloodlines collides with destiny in this NOXA trailer.',
        thumbnailUrl: 'https://www.noxafilmstudio.com/trailer3/images/blade_trailer_thumbnail.png',
        uploadDate: '2025-01-01',
        duration: 'PT9M11S',
        embedUrl: 'https://www.noxafilmstudio.com/trailer3/',
        contentUrl: 'https://www.noxafilmstudio.com/trailer3/videos/blade_trailer1.mp4',
      },
    },
    '/applynow/': {
      title: 'Apply as a Director | NOXA FILM',
      description: 'Apply to join NOXA Film Studio as a director and collaborate on AI-native cinema.',
      ogType: 'website',
    },
    '/submitscript/': {
      title: 'Submit a Script | NOXA FILM',
      description: 'Submit your screenplay for consideration by NOXA Film Studio.',
      ogType: 'website',
    },
    '/investment_page/': {
      title: 'Invest in NOXA Film Studio',
      description: 'Explore investment opportunities in NOXA Film Studio and its AI-native productions.',
      ogType: 'website',
    },
    '/privacy/': {
      title: 'Privacy Policy | NOXA FILM',
      description: 'Read the NOXA Film privacy policy and data practices.',
      ogType: 'website',
    },
    '/terms/': {
      title: 'Terms of Service | NOXA FILM',
      description: 'Review NOXA Film Studio terms and conditions.',
      ogType: 'website',
    },
  },
}
